### ISSUE TITLE
highRes images not showing with demo mockup

### ISSUE THREAD

**Issue by mikhuang** [pixelunion/Extended-Tumblr-Photoset#10]
Highres images target `.photo img` on line 301 of pxuPhotoset.js, which doesn't exist in the demo markup. It seems either the .js should change or the markup should change like:

``` html
  ... 
  {block:Photos}
    <div class="photo-data">
      <div class="pxu-photo photo">
        <img alt="{PhotoAlt}"...
```

Thanks for the awesome library!

**Comment by graygilmore** [comment]
Thanks for this! Sorry for the late reply, should be fixed up!
