### ISSUE TITLE
next image not shown in slideshow

### ISSUE THREAD

**Issue by leonidkozhukh** [pixelunion/Extended-Tumblr-Photoset#12]
only the previous image, along with the image that was clicked, is shown in the slideshow. the next image in the series does not appear on the right of the image that was clicked.

eg: clicking the first image in the photoset opens the lightbox with no previous or next image.

**Comment by graygilmore** [comment]
This is actually a problem with the Tumblr modal itself. Since we're just using Tumblr's default setup, it's something that they'll have to push a fix for.

The plugin _does_ allow for you to hook up your own modal (lightbox) if you think the Tumblr one is insufficient.
