### ISSUE TITLE
Used this to build a photoset plugin in CommonJS format

### ISSUE THREAD

**Issue by chadfurman** [pixelunion/Extended-Tumblr-Photoset#21]
Hiya,

Thank you for this!  It was quite inspirational.

I built an albumPhotoset and a rollover plugin for my tumblr template using the logic in your code, and wanted to share with you.

Many well wishes!

https://github.com/shadesoflight/tumblr-template-sass/blob/master/theme/js/main.js
https://github.com/shadesoflight/tumblr-template-sass/tree/master/theme/libs/tumblr-photoset
https://github.com/shadesoflight/tumblr-template-sass/blob/master/package.json#L22

**Comment by graygilmore** [comment]
Nice! Glad it helped.

**Comment by jarednorman** [comment]
:sailboat:
