### ISSUE TITLE
Open the lightbox on photo click (as opposed to zoom icon click)

### ISSUE THREAD

**Issue by ghost** [pixelunion/Extended-Tumblr-Photoset#9]
I want to be able to activate the photoset lightbox by clicking on an image in the photoset, not by hovering, then clicking the zoom icon. If this is possible, could someone explain how to do it?

**Comment by graygilmore** [comment]
Right now the plugin is using this as its click function:

``` js
$('.tumblr-box').on('click', function (e) {
    e.preventDefault();

    var clicked = $(this);
    var photoSlideshow = clicked.parents(settings.photoset).attr('id');
    tumblrLightbox(clicked, photoSlideshow);
});
```

You'd need to change that to look something like this:

``` js
$(settings.photo).on('click', function (e) {
    e.preventDefault();

    var clicked = $(this);
    var photoSlideshow = clicked.parents(settings.photoset).attr('id');
    tumblrLightbox(clicked, photoSlideshow);
});
```

And you can simply remove the hover functions from the JS completely if you don't want them. If you want users to be able to hover and also hit the zoom icon you could do:

``` js
$(settings.photo + ', .tumblr-box').on('click', function (e) {
    ...
});
```

**Comment by ghost** [comment]
Wow that worked wonderfully! (I went ahead and hid the icons class with "display:none" so as not to cause confusion)

I also added an empty a tag around the img in the photoset block, so when you hover over the photo the cursor changes (perhaps there is a more elegant way to do that, but this works for now!)

Thank you so much for all your help, it's exactly what I needed!

**Comment by graygilmore** [comment]
Instead of adding an empty `<a>` tag, you can just add `cursor: pointer;` to your CSS file for the image.

``` css
.pxu-photo img {
    cursor: pointer;
}
```
